# Generated by Django 5.1.2 on 2024-11-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userex',
            name='full_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
