# Generated by Django 5.1.2 on 2024-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0003_userex_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userex',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
