# Generated by Django 5.1.5 on 2025-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0007_alter_userex_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userex',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
