# Generated by Django 5.1.5 on 2025-08-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0009_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userex',
            name='is_friend',
            field=models.CharField(blank=True, default=False, max_length=150, null=True),
        ),
    ]
