# Generated by Django 5.1.5 on 2025-08-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0010_userex_is_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userex',
            name='is_friend',
        ),
    ]
